const INGREDIENT_DATA = [
    { name: "Esterquat 65", price: 70.40 },
    { name: "Rožu ziedūdens", price: 62.93 },
    { name: "SCI Sodium Cocoyl Isethionate", price: 31.84 },
    { name: "Saulespuķu eļļa", price: 18.88 },
    { name: "Makadāmijas riekstu eļļa", price: 54.55 },
    { name: "Emulsificējošais vasks", price: 70 },
    { name: "Glicerīns", price: 21.77 },
    { name: "Šī sviests", price: 31.11 },
    { name: "Kakao sviests", price: 30 },
    { name: "Pienskābe", price: 175 },
    { name: "Stearīnskābe", price: 35 },
    { name: "D-pantenols", price: 178.13 },
    { name: "Kviešu asnu eļļa", price: 88.89 },
    { name: "Savvaļas rožu eļļa", price: 233.33 },
    { name: "BTMS-50", price: 85 },
    { name: "Cetilalkohols", price: 35 },
    { name: "Biešu pulveris", price: 57 },
    { name: "Olivem 900", price: 115 },
    { name: "Cosgard", price: 250 },
    { name: "Jogurta pulveris", price: 20 },
    { name: "Kukurūzas ciete", price: 4.48 },
    { name: "Destilēts ūdens", price: 1 },
];
